# Generated by Django 4.1.6 on 2023-03-17 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 17, 6, 12, 55, 728199, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
